### ISSUE TITLE
[PE-D] Inaccurate command notes in Feature section of user guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F09-3/tp#148]
Under the section **Features**, on the notes about the command format, the command `list` is given as an example under extraneous parameters for commands that do not take in parameters are not allowed.

However, the 'list' command on its own does not exist and does have to take parameters to know which data type to be listed.

The example given is thus, inaccurate.

![image.png](https://raw.githubusercontent.com/LapisRaider/ped/main/files/df98ef06-d0ad-4b30-bf44-5c3ef784e47d.png)

![image.png](https://raw.githubusercontent.com/LapisRaider/ped/main/files/114b506f-a310-42e8-8c58-4c047bfee2ac.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: LapisRaider/ped#3

**Comment by zzkzzzz** [comment]
we never mention that `list` is a command in our UG.
