### ISSUE TITLE
[PE-D] Unable to edit client description 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-F09-3/tp#166]
![Screenshot 2022-04-01 at 2.52.01 PM.png](https://raw.githubusercontent.com/Dineshraj555/ped/main/files/cc01ed8a-d412-4810-b19f-2348e21c785e.png)

I think this was not implemented right, other fields of the clients can edit well only description cannot be edited. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Dineshraj555/ped#7

**Comment by zzkzzzz** [comment]
UG bug. We don't have a description tag for a client. Issue fixed.
