### ISSUE TITLE
[PE-D] Comparing person using names instead of other attributes like email/phone number

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-F09-3/tp#188]
Since it is possible for two people to have the same name, especially for a clientele app like an insurance application, it restricts the user's ability to add people with the same name. This may result in people not wanting to use the application since it is a limitation.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: lkldev/ped#13

**Comment by zzkzzzz** [comment]
we wont fix this

**Comment by zzkzzzz** [comment]
We will mention this in UG that client name is the primary key in client list (client name cant duplicate)
